title: Annuity Loan Repayment Planner
logo: /assets/img/money.jpeg
description: Creates a CSV file of an annuity loan repayment plan
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
