title: Annuity Loan Repayment Planner
logo: /assets/img/GitHub-Mark-120px-plus.png
description: Creates CSV file of Annuity loan repayment plan
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
